source "https://rubygems.org"

# Jekyll and plugins
gem "jekyll", "~> 4.3"
gem "jekyll-theme-slate"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
